_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 103
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.2
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
batchsize:
    value: 1
cam_dir:
    value: ../audio_cam
checkpoint_path:
    value: null
checkpoint_step:
    value: 20000
control_type:
    value: energy_video
csv_file:
    value: ../audiovisual_filenames.csv
ddim_steps:
    value: 200
duration:
    value: 5
eval_epoch:
    value: 1
eval_step:
    value: 1000
guidance_scale:
    value: 3
lr:
    value: 0.0001
lr_gamma:
    value: 0.1
lr_step:
    value: 10
num_epochs:
    value: 100
num_workers:
    value: 8
phi_ckpt_path:
    value: ./ckpts/phi_vggsound.ckpt
project_name:
    value: CAM_Evaluation
re_encode:
    value: false
resume:
    value: false
run_name:
    value: Main_test1
save_path:
    value: ./results_resume
seed:
    value: 42
synchformer_exp:
    value: 24-01-04T16-39-21
test_batch_size:
    value: 8
test_cam_dir:
    value: ./test_dataset_real
test_csv_file:
    value: ./test_dataset_real/test_videos_filenames.csv
test_video_dir:
    value: ./test_dataset_real/AVsync_videos_25fps
train_batch_size:
    value: 32
video_dir:
    value: ../video_25fps
